export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCEEDED = 'GET_GROUPS_SUCCEEDED';
export const GET_GROUPS_FAILED = 'GET_GROUPS_FAILED';

export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_SUCCEEDED = 'GET_GROUP_SUCCEEDED';
export const GET_GROUP_FAILED = 'GET_GROUP_FAILED';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_SUCCEEDED = 'CREATE_GROUP_SUCCEEDED';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';

export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_GROUP_SUCCEEDED = 'UPDATE_GROUP_SUCCEEDED';
export const UPDATE_GROUP_FAILED = 'UPDATE_GROUP_FAILED';

export const GET_GROUP_SURVEYS = 'GET_GROUP_SURVEYS';
export const GET_GROUP_SURVEYS_SUCCEEDED = 'GET_GROUP_SURVEYS_SUCCEEDED';
export const GET_GROUP_SURVEYS_FAILED = 'GET_GROUP_SURVEYS_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const CREATE_SURVEY = 'CREATE_SURVEY';
export const CREATE_SURVEY_SUCCEEDED = 'CREATE_SURVEY_SUCCEEDED';
export const CREATE_SURVEY_FAILED = 'CREATE_SURVEY_FAILED';

export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEY_SUCCEEDED = 'GET_SURVEY_SUCCEEDED';
export const GET_SURVEY_FAILED = 'GET_SURVEY_FAILED';


export const GET_SURVEY_QUESTIONS = 'GET_SURVEY_QUESTIONS';
export const GET_SURVEY_QUESTIONS_SUCCEEDED = 'GET_SURVEY_QUESTIONS_SUCCEEDED';
export const GET_SURVEY_QUESTIONS_FAILED = 'GET_SURVEY_QUESTIONS_FAILED';

export const GET_SURVEY_RESPONSES = 'GET_SURVEY_RESPONSES';
export const GET_SURVEY_RESPONSES_SUCCEEDED = 'GET_SURVEY_RESPONSES_SUCCEEDED';
export const GET_SURVEY_RESPONSES_FAILED = 'GET_SURVEY_RESPONSES_FAILED';


export const ADD_SURVEY_QUESTION = 'ADD_SURVEY_QUESTION';
export const ADD_SURVEY_QUESTION_SUCCEEDED = 'ADD_SURVEY_QUESTION_SUCCEEDED';
export const ADD_SURVEY_QUESTION_FAILED = 'ADD_SURVEY_QUESTION_FAILED';

export const GET_SURVEY_USERS = 'GET_SURVEY_USERS';
export const GET_SURVEY_USERS_SUCCEEDED = 'GET_SURVEY_USERS_SUCCEEDED';
export const GET_SURVEY_USERS_FAILED = 'GET_SURVEY_USERS_FAILED';


export const ADD_SURVEY_USER = 'ADD_SURVEY_USER';
export const ADD_SURVEY_USER_SUCCEEDED = 'ADD_SURVEY_USER_SUCCEEDED';
export const ADD_SURVEY_USER_FAILED = 'ADD_SURVEY_USER_FAILED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCEEDED = 'CREATE_USER_SUCCEEDED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const UPDATE_SURVEY = 'UPDATE_SURVEY';
export const UPDATE_SURVEY_SUCCEEDED = 'UPDATE_SURVEY_SUCCEEDED';
export const UPDATE_SURVEY_FAILED = 'UPDATE_SURVEY_FAILED';

export const ADD_BRANCH_QUESTION = 'ADD_BRANCH_QUESTION';
export const ADD_BRANCH_QUESTION_SUCCEEDED = 'ADD_BRANCH_QUESTION_SUCCEEDED';
export const ADD_BRANCH_QUESTION_FAILED = 'ADD_BRANCH_QUESTION_FAILED';

