export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCEEDED = 'GET_GROUPS_SUCCEEDED';
export const GET_GROUPS_FAILED = 'GET_GROUPS_FAILED';

export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_SUCCEEDED = 'GET_GROUP_SUCCEEDED';
export const GET_GROUP_FAILED = 'GET_GROUP_FAILED';

export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_SUCCEEDED = 'CREATE_GROUP_SUCCEEDED';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';

export const GET_GROUP_SURVEYS = 'GET_GROUP_SURVEYS';
export const GET_GROUP_SURVEYS_SUCCEEDED = 'GET_GROUP_SURVEYS_SUCCEEDED';
export const GET_GROUP_SURVEYS_FAILED = 'GET_GROUP_SURVEYS_FAILED';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const CREATE_SURVEY = 'CREATE_SURVEY';
export const CREATE_SURVEY_SUCCEEDED = 'CREATE_SURVEY_SUCCEEDED';
export const CREATE_SURVEY_FAILED = 'CREATE_SURVEY_FAILED';
